spring.application.name=fut-order


# 1. CREDENCIAIS DO BANCO DE DADOS

# A URL aponta para a sua máquina (localhost), porta 3306,
spring.datasource.url=jdbc:mysql://localhost:3306/fut_order_db?serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
//COLOQUE A SUA SENHA AQUI:
spring.datasource.password=${DB_PASSWORD:sua_senha_local_aqui}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. CONFIGURAÇÕES DO HIBERNATE/JPA

# Exibe no console os comandos SQL gerados (excelente para estudos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# O "update" instrui o Hibernate a ler suas classes @Entity e criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update